/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.List;

import controller.VendedorController;
import javax.swing.table.DefaultTableModel;

public class TelaCadastroVendedor1 extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendedor
     */
    public TelaCadastroVendedor1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastroVendedor = new javax.swing.JLabel();
        painelSuperior = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        painelCentro = new javax.swing.JPanel();
        txtSalarioLiquido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblPremioMeta = new javax.swing.JLabel();
        txtPorcentagemComissao = new javax.swing.JTextField();
        txtComissaoVendas = new javax.swing.JTextField();
        txtTotalVendasMensal = new javax.swing.JTextField();
        lblComissaoVendas = new javax.swing.JLabel();
        lblSalarioFinal = new javax.swing.JLabel();
        lblTotalVendasMensal = new javax.swing.JLabel();
        lblPorcentagemComissao = new javax.swing.JLabel();
        lblSalarioLiquido = new javax.swing.JLabel();
        txtSalarioFinal = new javax.swing.JTextField();
        txtPremioMeta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        painelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVendedor = new javax.swing.JTable();
        painelBotoes = new javax.swing.JPanel();
        btnInserir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnConsultarPorId = new javax.swing.JButton();
        btnConsultarTodos = new javax.swing.JButton();
        btnCalcularComissaoVendas = new javax.swing.JButton();
        btnCalcularSalarioFinal = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastroVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCadastroVendedor.setText("CADASTRO VENDEDOR");

        lblID.setText("ID:");

        lblNome.setText("Nome:");

        lblCPF.setText("CPF:");

        lblEndereco.setText("Endereço:");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addComponent(lblCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco))
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel12.setText("x");

        jLabel13.setText("+");

        jLabel14.setText("+");

        jLabel16.setText("=");

        lblPremioMeta.setText("Premio Meta:");

        txtComissaoVendas.setEditable(false);

        lblComissaoVendas.setText("COMISSÃO VENDAS:");

        lblSalarioFinal.setText("SALÁRIO FINAL:");

        lblTotalVendasMensal.setText("Total Vendas Mensal:");

        lblPorcentagemComissao.setText("% Comissão:");

        lblSalarioLiquido.setText("Salário Líquido:");

        txtSalarioFinal.setEditable(false);

        txtPremioMeta.setEditable(false);

        jLabel17.setText("=");

        javax.swing.GroupLayout painelCentroLayout = new javax.swing.GroupLayout(painelCentro);
        painelCentro.setLayout(painelCentroLayout);
        painelCentroLayout.setHorizontalGroup(
            painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCentroLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCentroLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblComissaoVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtComissaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPremioMeta)
                            .addComponent(txtPremioMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCentroLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblSalarioLiquido))
                            .addGroup(painelCentroLayout.createSequentialGroup()
                                .addComponent(txtSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelCentroLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblSalarioFinal))
                            .addComponent(txtSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelCentroLayout.createSequentialGroup()
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalVendasMensal)
                            .addComponent(txtTotalVendasMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCentroLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtPorcentagemComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelCentroLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblPorcentagemComissao)))))
                .addGap(26, 26, 26))
        );
        painelCentroLayout.setVerticalGroup(
            painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCentroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalVendasMensal)
                    .addComponent(lblPorcentagemComissao))
                .addGap(3, 3, 3)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalVendasMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcentagemComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioLiquido)
                    .addComponent(lblComissaoVendas)
                    .addComponent(lblPremioMeta)
                    .addComponent(lblSalarioFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComissaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPremioMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Endereço", "Total Vendas Mensal", "% Comissão", "Salário Líquido", "Prêmio Meta", "Comissão Vendas", "Salário Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaVendedor);
        if (tabelaVendedor.getColumnModel().getColumnCount() > 0) {
            tabelaVendedor.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelaVendedor.getColumnModel().getColumn(4).setMinWidth(120);
            tabelaVendedor.getColumnModel().getColumn(6).setMinWidth(90);
            tabelaVendedor.getColumnModel().getColumn(8).setMinWidth(100);
        }

        javax.swing.GroupLayout painelTabelaLayout = new javax.swing.GroupLayout(painelTabela);
        painelTabela.setLayout(painelTabelaLayout);
        painelTabelaLayout.setHorizontalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2)
                .addGap(25, 25, 25))
        );
        painelTabelaLayout.setVerticalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnConsultarPorId.setText("Consultar por ID");
        btnConsultarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPorIdActionPerformed(evt);
            }
        });

        btnConsultarTodos.setText("Consultar Todos");
        btnConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTodosActionPerformed(evt);
            }
        });

        btnCalcularComissaoVendas.setText("Calcular COMISSÃO VENDAS");
        btnCalcularComissaoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularComissaoVendasActionPerformed(evt);
            }
        });

        btnCalcularSalarioFinal.setText("Calcular SALÁRIO FINAL");
        btnCalcularSalarioFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSalarioFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar))
                    .addGroup(painelBotoesLayout.createSequentialGroup()
                        .addComponent(btnConsultarPorId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultarTodos))
                    .addComponent(btnCalcularComissaoVendas)
                    .addComponent(btnCalcularSalarioFinal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAtualizar)
                    .addComponent(btnDeletar))
                .addGap(18, 18, 18)
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarPorId)
                    .addComponent(btnConsultarTodos))
                .addGap(36, 36, 36)
                .addComponent(btnCalcularComissaoVendas)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularSalarioFinal)
                .addContainerGap())
        );

        lblMensagem.setText("Mensagem:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 468, Short.MAX_VALUE)
                .addComponent(lblCadastroVendedor)
                .addGap(342, 342, 342))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblMensagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelCentro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCadastroVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensagem)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularComissaoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularComissaoVendasActionPerformed
        String[] dados = {
            txtPorcentagemComissao.getText(),
            txtTotalVendasMensal.getText()
        };

        String valorComissaoVendas = VendedorController.calcularComissaoVendas(dados);

        txtComissaoVendas.setText(valorComissaoVendas);
        this.definirPremioMeta();
    }//GEN-LAST:event_btnCalcularComissaoVendasActionPerformed

    public void definirPremioMeta() {
        String valorPremioMeta = VendedorController.definirPremioMeta(txtComissaoVendas.getText());

        txtPremioMeta.setText(valorPremioMeta);
    }

    private void btnCalcularSalarioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSalarioFinalActionPerformed
        String[] dados = {
            txtComissaoVendas.getText(),
            txtPremioMeta.getText(),
            txtSalarioLiquido.getText()
        };

        String valorSalarioFinal = VendedorController.calcularSalarioFinal(dados);

        txtSalarioFinal.setText(valorSalarioFinal);
    }//GEN-LAST:event_btnCalcularSalarioFinalActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        String dados[] = {
            txtNome.getText(),
            txtCPF.getText(),
            txtEndereco.getText(),
            txtTotalVendasMensal.getText(),
            txtPorcentagemComissao.getText(),
            txtSalarioLiquido.getText(),
            txtPremioMeta.getText(),
            txtComissaoVendas.getText(),
            txtSalarioFinal.getText()
        };

        try {
            VendedorController.inserirVendedor(dados);
            lblMensagem.setText("Mensagem: Vendedor inserido com sucesso");
            txtNome.setText("");
            txtCPF.setText("");
            txtEndereco.setText("");
            txtTotalVendasMensal.setText("");
            txtPorcentagemComissao.setText("");
            txtSalarioLiquido.setText("");
            txtPremioMeta.setText("");
            txtComissaoVendas.setText("");
            txtSalarioFinal.setText("");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao inserir vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String dados[] = {
            txtNome.getText(),
            txtCPF.getText(),
            txtEndereco.getText(),
            txtTotalVendasMensal.getText(),
            txtPorcentagemComissao.getText(),
            txtSalarioLiquido.getText(),
            txtPremioMeta.getText(),
            txtComissaoVendas.getText(),
            txtSalarioFinal.getText(),
            txtID.getText()
        };

        try {
            VendedorController.atualizarVendedor(dados);
            lblMensagem.setText("Mensagem: Vendedor atualizado com sucesso");
            txtNome.setText("");
            txtCPF.setText("");
            txtEndereco.setText("");
            txtTotalVendasMensal.setText("");
            txtPorcentagemComissao.setText("");
            txtSalarioLiquido.setText("");
            txtPremioMeta.setText("");
            txtComissaoVendas.setText("");
            txtSalarioFinal.setText("");
            txtID.setText("");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao atualizado vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        String dado = txtID.getText();

        try {
            VendedorController.deletarVendedor(dado);
            lblMensagem.setText("Mensagem: Vendedor deletado com sucesso");
            txtID.setText("");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao deletar vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnConsultarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPorIdActionPerformed
        String dado = txtID.getText();

        try {
            String[] atributos = VendedorController.consultarPorId(dado);
            if (atributos != null) {
                lblMensagem.setText("Mensagem: Vendedor encontrado com sucesso");
                txtNome.setText(atributos[0]);
                txtCPF.setText(atributos[1]);
                txtEndereco.setText(atributos[2]);
                txtTotalVendasMensal.setText(atributos[3]);
                txtPorcentagemComissao.setText(atributos[4]);
                txtSalarioLiquido.setText(atributos[5]);
                txtPremioMeta.setText(atributos[6]);
                txtComissaoVendas.setText(atributos[7]);
                txtSalarioFinal.setText(atributos[8]);
            } else {
                lblMensagem.setText("Mensagem: Vendedor não encontrado");
                txtNome.setText("");
                txtCPF.setText("");
                txtEndereco.setText("");
                txtTotalVendasMensal.setText("");
                txtPorcentagemComissao.setText("");
                txtSalarioLiquido.setText("");
                txtPremioMeta.setText("");
                txtComissaoVendas.setText("");
                txtSalarioFinal.setText("");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao encontrar o Vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultarPorIdActionPerformed

    private void btnConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTodosActionPerformed
        DefaultTableModel modeloTab = (DefaultTableModel) tabelaVendedor.getModel();
        modeloTab.setNumRows(0);
        try {
            List<String[]> lvend = VendedorController.consultarTodos();
            for (String[] vend : lvend) {
                modeloTab.addRow(vend);
            }
            lblMensagem.setText("Mensagem: Consulta realizada com sucesso");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao consultar todos os Vendedores " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVendedor1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCalcularComissaoVendas;
    private javax.swing.JButton btnCalcularSalarioFinal;
    private javax.swing.JButton btnConsultarPorId;
    private javax.swing.JButton btnConsultarTodos;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastroVendedor;
    private javax.swing.JLabel lblComissaoVendas;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPorcentagemComissao;
    private javax.swing.JLabel lblPremioMeta;
    private javax.swing.JLabel lblSalarioFinal;
    private javax.swing.JLabel lblSalarioLiquido;
    private javax.swing.JLabel lblTotalVendasMensal;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCentro;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JTable tabelaVendedor;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtComissaoVendas;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPorcentagemComissao;
    private javax.swing.JTextField txtPremioMeta;
    private javax.swing.JTextField txtSalarioFinal;
    private javax.swing.JTextField txtSalarioLiquido;
    private javax.swing.JTextField txtTotalVendasMensal;
    // End of variables declaration//GEN-END:variables
}
