/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.List;

import controller.VendedorController;
import javax.swing.table.DefaultTableModel;

public class TelaCadastroVendedor extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendedor
     */
    public TelaCadastroVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastroVendedor = new javax.swing.JLabel();
        painelTabela = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVendedor = new javax.swing.JTable();
        lblMensagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        painelSuperior = new javax.swing.JPanel();
        lblTotalVendasMensal = new javax.swing.JLabel();
        txtTotalVendasMensal = new javax.swing.JTextField();
        lblPremioMeta = new javax.swing.JLabel();
        txtPremioMeta = new javax.swing.JTextField();
        lblPorcentagemComissao = new javax.swing.JLabel();
        txtPorcentagemComissao = new javax.swing.JTextField();
        lblSalarioLiquido = new javax.swing.JLabel();
        txtSalarioLiquido = new javax.swing.JTextField();
        lblComissaoVendas = new javax.swing.JLabel();
        txtComissaoVendas = new javax.swing.JTextField();
        txtSalarioFinal = new javax.swing.JTextField();
        lblSalarioFinal = new javax.swing.JLabel();
        btnCalcularComissaoVendas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCalcularSalarioFinal = new javax.swing.JButton();
        painelCentro = new javax.swing.JPanel();
        btnInserir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnConsultarPorId = new javax.swing.JButton();
        btnConsultarTodos = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atividade CRUD");
        setResizable(false);

        lblCadastroVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCadastroVendedor.setText("CADASTRO VENDEDOR");

        tabelaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Endereço", "Total Vendas Mensal", "% Comissão", "Salário Líquido", "Prêmio Meta", "Comissão Vendas", "Salário Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaVendedor);
        if (tabelaVendedor.getColumnModel().getColumnCount() > 0) {
            tabelaVendedor.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelaVendedor.getColumnModel().getColumn(4).setMinWidth(120);
            tabelaVendedor.getColumnModel().getColumn(6).setMinWidth(90);
            tabelaVendedor.getColumnModel().getColumn(8).setMinWidth(100);
        }

        lblMensagem.setText("Mensagem:");

        javax.swing.GroupLayout painelTabelaLayout = new javax.swing.GroupLayout(painelTabela);
        painelTabela.setLayout(painelTabelaLayout);
        painelTabelaLayout.setHorizontalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTabelaLayout.createSequentialGroup()
                        .addComponent(lblMensagem)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelTabelaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(25, 25, 25))))
        );
        painelTabelaLayout.setVerticalGroup(
            painelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        lblTotalVendasMensal.setText("Total Vendas Mensal:");

        lblPremioMeta.setText("Prêmio Meta:");

        txtPremioMeta.setEditable(false);

        lblPorcentagemComissao.setText("% Comissão:");

        lblSalarioLiquido.setText(" Salário Líquido:");

        lblComissaoVendas.setText(" Comissão Vendas:");

        txtComissaoVendas.setEditable(false);

        txtSalarioFinal.setEditable(false);

        lblSalarioFinal.setText(" Salário Final:");

        btnCalcularComissaoVendas.setText("Calcular Comissão Vendas");
        btnCalcularComissaoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularComissaoVendasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("Comissão Vendas = Total Vendas Mensal * % Comissão");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Salário Final = Comissão Vendas + Prêmio Meta + Salário Líquido");

        btnCalcularSalarioFinal.setText("Calcular Salário Final");
        btnCalcularSalarioFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularSalarioFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalVendasMensal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPremioMeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPremioMeta)
                    .addComponent(txtTotalVendasMensal))
                .addGap(48, 48, 48)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelSuperiorLayout.createSequentialGroup()
                                .addComponent(lblSalarioLiquido)
                                .addGap(48, 48, 48)
                                .addComponent(lblSalarioFinal))
                            .addGroup(painelSuperiorLayout.createSequentialGroup()
                                .addComponent(txtSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(txtSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelSuperiorLayout.createSequentialGroup()
                                .addComponent(lblPorcentagemComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lblComissaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addComponent(txtPorcentagemComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtComissaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3))
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcularComissaoVendas)
                    .addComponent(btnCalcularSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelSuperiorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblComissaoVendas, lblPorcentagemComissao, lblPremioMeta, lblSalarioFinal, lblSalarioLiquido, lblTotalVendasMensal, txtComissaoVendas, txtPremioMeta, txtSalarioFinal, txtSalarioLiquido});

        painelSuperiorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalVendasMensal)
                    .addComponent(lblPorcentagemComissao)
                    .addComponent(lblComissaoVendas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalVendasMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcentagemComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComissaoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremioMeta)
                    .addComponent(lblSalarioLiquido)
                    .addComponent(lblSalarioFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPremioMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularComissaoVendas)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularSalarioFinal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnConsultarPorId.setText("Consultar por ID");
        btnConsultarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPorIdActionPerformed(evt);
            }
        });

        btnConsultarTodos.setText("Consultar Todos");
        btnConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTodosActionPerformed(evt);
            }
        });

        lblID.setText(" ID:");

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });

        lblEndereco.setText(" Endereço:");

        lblNome.setText(" Nome:");

        lblCPF.setText(" CPF:");

        javax.swing.GroupLayout painelCentroLayout = new javax.swing.GroupLayout(painelCentro);
        painelCentro.setLayout(painelCentroLayout);
        painelCentroLayout.setHorizontalGroup(
            painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCentroLayout.createSequentialGroup()
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCPF)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEndereco)
                            .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtNome)))
                    .addGroup(painelCentroLayout.createSequentialGroup()
                        .addComponent(btnInserir)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar))
                    .addGroup(painelCentroLayout.createSequentialGroup()
                        .addComponent(btnConsultarPorId)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarTodos)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        painelCentroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCPF, lblID});

        painelCentroLayout.setVerticalGroup(
            painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(lblEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar))
                .addGap(24, 24, 24)
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarTodos)
                    .addComponent(btnConsultarPorId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(painelCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(lblCadastroVendedor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCadastroVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(painelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularComissaoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularComissaoVendasActionPerformed
        String[] dados = {
            txtPorcentagemComissao.getText(),
            txtTotalVendasMensal.getText()
        };

        String valorComissaoVendas = VendedorController.calcularComissaoVendas(dados);

        txtComissaoVendas.setText(valorComissaoVendas);
        this.definirPremioMeta();
    }//GEN-LAST:event_btnCalcularComissaoVendasActionPerformed

    public void definirPremioMeta() {
        String valorPremioMeta = VendedorController.definirPremioMeta(txtComissaoVendas.getText());

        txtPremioMeta.setText(valorPremioMeta);
    }

    private void btnCalcularSalarioFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularSalarioFinalActionPerformed
        String[] dados = {
            txtComissaoVendas.getText(),
            txtPremioMeta.getText(),
            txtSalarioLiquido.getText()
        };

        String valorSalarioFinal = VendedorController.calcularSalarioFinal(dados);

        txtSalarioFinal.setText(valorSalarioFinal);
    }//GEN-LAST:event_btnCalcularSalarioFinalActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        String dados[] = {
            txtNome.getText(),
            txtCPF.getText(),
            txtEndereco.getText(),
            txtTotalVendasMensal.getText(),
            txtPorcentagemComissao.getText(),
            txtSalarioLiquido.getText(),
            txtPremioMeta.getText(),
            txtComissaoVendas.getText(),
            txtSalarioFinal.getText()
        };

        try {
            VendedorController.inserirVendedor(dados);
            lblMensagem.setText("Mensagem: Vendedor inserido com sucesso");
            txtNome.setText("");
            txtCPF.setText("");
            txtEndereco.setText("");
            txtTotalVendasMensal.setText("");
            txtPorcentagemComissao.setText("");
            txtSalarioLiquido.setText("");
            txtPremioMeta.setText("");
            txtComissaoVendas.setText("");
            txtSalarioFinal.setText("");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao inserir vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String dados[] = {
            txtNome.getText(),
            txtCPF.getText(),
            txtEndereco.getText(),
            txtTotalVendasMensal.getText(),
            txtPorcentagemComissao.getText(),
            txtSalarioLiquido.getText(),
            txtPremioMeta.getText(),
            txtComissaoVendas.getText(),
            txtSalarioFinal.getText(),
            txtID.getText()
        };

        try {
            VendedorController.atualizarVendedor(dados);
            lblMensagem.setText("Mensagem: Vendedor atualizado com sucesso");
            txtNome.setText("");
            txtCPF.setText("");
            txtEndereco.setText("");
            txtTotalVendasMensal.setText("");
            txtPorcentagemComissao.setText("");
            txtSalarioLiquido.setText("");
            txtPremioMeta.setText("");
            txtComissaoVendas.setText("");
            txtSalarioFinal.setText("");
            txtID.setText("");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao atualizado vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        String dado = txtID.getText();

        try {
            VendedorController.deletarVendedor(dado);
            lblMensagem.setText("Mensagem: Vendedor deletado com sucesso");
            txtID.setText("");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao deletar vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnConsultarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPorIdActionPerformed
        String dado = txtID.getText();

        try {
            String[] atributos = VendedorController.consultarPorId(dado);
            if (atributos != null) {
                lblMensagem.setText("Mensagem: Vendedor encontrado com sucesso");
                txtNome.setText(atributos[0]);
                txtCPF.setText(atributos[1]);
                txtEndereco.setText(atributos[2]);
                txtTotalVendasMensal.setText(atributos[3]);
                txtPorcentagemComissao.setText(atributos[4]);
                txtSalarioLiquido.setText(atributos[5]);
                txtPremioMeta.setText(atributos[6]);
                txtComissaoVendas.setText(atributos[7]);
                txtSalarioFinal.setText(atributos[8]);
            } else {
                lblMensagem.setText("Mensagem: Vendedor não encontrado");
                txtNome.setText("");
                txtCPF.setText("");
                txtEndereco.setText("");
                txtTotalVendasMensal.setText("");
                txtPorcentagemComissao.setText("");
                txtSalarioLiquido.setText("");
                txtPremioMeta.setText("");
                txtComissaoVendas.setText("");
                txtSalarioFinal.setText("");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao encontrar o Vendedor " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultarPorIdActionPerformed

    private void btnConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTodosActionPerformed
        DefaultTableModel modeloTab = (DefaultTableModel) tabelaVendedor.getModel();
        modeloTab.setNumRows(0);
        try {
            List<String[]> lvend = VendedorController.consultarTodos();
            for (String[] vend : lvend) {
                modeloTab.addRow(vend);
            }
            lblMensagem.setText("Mensagem: Consulta realizada com sucesso");
        } catch (SQLException | ClassNotFoundException ex) {
            lblMensagem.setText("Mensagem: Falha ao consultar todos os Vendedores " + ex.getMessage());
        }
    }//GEN-LAST:event_btnConsultarTodosActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCalcularComissaoVendas;
    private javax.swing.JButton btnCalcularSalarioFinal;
    private javax.swing.JButton btnConsultarPorId;
    private javax.swing.JButton btnConsultarTodos;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCadastroVendedor;
    private javax.swing.JLabel lblComissaoVendas;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPorcentagemComissao;
    private javax.swing.JLabel lblPremioMeta;
    private javax.swing.JLabel lblSalarioFinal;
    private javax.swing.JLabel lblSalarioLiquido;
    private javax.swing.JLabel lblTotalVendasMensal;
    private javax.swing.JPanel painelCentro;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JTable tabelaVendedor;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtComissaoVendas;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPorcentagemComissao;
    private javax.swing.JTextField txtPremioMeta;
    private javax.swing.JTextField txtSalarioFinal;
    private javax.swing.JTextField txtSalarioLiquido;
    private javax.swing.JTextField txtTotalVendasMensal;
    // End of variables declaration//GEN-END:variables
}
